[package]
name = "edinburgh"
version = "0.1.0"
authors = ["Sascha Smolkov <sascha.smolkov@gmail.com>"]
edition = "2018"
description = "Edinburg sensor linux fs driver"
keywords = ["sensor","driver","ndir"]
categories = ["linux", "automatic", "sensor"]
repository = "https://github.com/lar-rs/edinburgh"
readme = "README.md"
license = "Apache-2.0 OR MIT"
# Is it maintained resolution time: `repository` is required.
# is-it-maintained-issue-resolution = { repository = "https://todo.sr.ht/~asmolkov/wqa" }
# Is it maintained percentage of open issues: `repository` is required.
# is-it-maintained-open-issues = { repository = "https://todo.sr.ht/~asmolkov/wqa" }



[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "lar-rs/edinburgh", branch = "master"}


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal = "0.2.3"
failure = "0.1.5"
# log
log = "0.4.8"
femme = "1.2.0"
# bigdecimal = { version = "0.1.0", features = ["serde"] }
# Serializer file format
serde_json = "1.0.40"
serde = { version = "1.0.101", features = ["derive"] }

paw = "1.0.0"
structopt = { version = "0.3.2", features = ["paw"] }
#Time date
chrono = "0.4.9"

lazy_static = "1.4.0"
qrcode = "0.11.0"
profont = "0.2.0"
# linux-embedded-hal = "0.2.2"
async-std = "0.99.6"
futures-preview = { version = "0.3.0-alpha.18", features = [ "async-await", "nightly" ] }
path-table = "1.0.0"
sysfs_gpio = "0.5.4"
gpio-utils = "0.3.0"
bincode = "1.1.4"
yansi = "0.5.0"
regex-automata = "0.1.8"
light-cli = "0.1.0"
nom = "5.0.1"
bytes = "0.4.12"
toml = "0.5.3"
uom = "0.25.0"
serial = "0.4.0"
ansi_term = "0.12.1"
pom = "3.0.2"
err-derive = "0.1.5"
regex = "1.3.1"
nb = "0.1.2"
# redis-async = "0.5.2"
